#!/usr/bin/env just --justfile

set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
set script-interpreter := ["pwsh.exe", "-NoLogo", "-Command"]

export WINGET_CONFIG := "winget.json"

[private]
default:
    @just --list

# export installed packages to WINGET_CONFIG
[windows]
export:
    winget export --ignore-warnings -s winget -o {{WINGET_CONFIG}}

# install packages from WINGET_CONFIG export
[windows]
import:
    winget import {{WINGET_CONFIG}}

# fix issue with JetBrains IDEA entry when installed through Jetbrains Toolbox
[windows]
[script]
fix-jetbrains-toolbox:
    try {
        $tempFile = "{{WINGET_CONFIG}}.temp"
        cp {{WINGET_CONFIG}} $tempFile
        ( jq --tab 'del( .Sources.[].Packages.[] | select (.PackageIdentifier == "JetBrains.IntelliJIDEA") )' $tempFile ) > {{WINGET_CONFIG}}
    } finally {
        if (Test-Path $tempFile) { Remove-Item $tempFile }
    }
