#!/usr/bin/env just --justfile

set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]
set script-interpreter := ["pwsh.exe", "-NoLogo", "-Command"]

export WINGET_CONFIG := "winget.json"

#
# •───────•°•❀  API  ❀•°•───────•
#

[private]
default:
    @just --list

# generate new config with fixes
[windows]
update: export fix-jetbrains-toolbox

# install packages from config
[windows]
install: import

#
# •───────•°•❀  winget  ❀•°•───────•
#

# export installed packages to WINGET_CONFIG
[windows]
[group("winget")]
[script]
export:
    Write-Host "Updating {{WINGET_CONFIG}}..." -NoNewline
    Write-Progress -CurrentOperation "Exporting" ( "Updating {{WINGET_CONFIG}}..." )
    winget export --ignore-warnings -s winget -o {{WINGET_CONFIG}}
    Write-Host "Done"

# install packages from WINGET_CONFIG export
[windows]
[group("winget")]
import:
    winget import {{WINGET_CONFIG}}

#
# •───────•°•❀  fixes  ❀•°•───────•
#

# fix issue with JetBrains IDEA entry when installed through Jetbrains Toolbox
[windows]
[group("fixes")]
[script]
fix-jetbrains-toolbox:
    try {
        # $DebugPreference = "Continue"
        Write-Host "Removing JetBrains.IntelliJIDEA..." -NoNewline
        $tempFile = "{{WINGET_CONFIG}}.temp"
        Copy-Item -Path {{WINGET_CONFIG}} -Destination $tempFile
        ( jq `
            --tab `
            'del( .Sources.[].Packages.[] | select (.PackageIdentifier == "JetBrains.IntelliJIDEA") )' `
            $tempFile `
        ) > {{WINGET_CONFIG}}
        Write-Host "Done"
    } finally {
        Write-Debug "Cleaning $tempFile"
        if (Test-Path $tempFile) { Remove-Item $tempFile }
    }
